### ISSUE TITLE
Dune stats do not adjust automatically

### ISSUE THREAD

**Issue by Retropex** [wtfhappenedinfeb2023/wtfhappenedinfeb2023.github.io#19]
<img width="491" alt="image" src="https://github.com/wtfhappenedinfeb2023/wtfhappenedinfeb2023.github.io/assets/74937347/a6428544-8ecc-4312-b4c0-ef2057de5c86">
<img width="491" alt="image" src="https://github.com/wtfhappenedinfeb2023/wtfhappenedinfeb2023.github.io/assets/74937347/f344a160-e6f5-4b0a-874e-1e7ce065cb4c">

**Comment by piratebiscuit** [comment]
Solved in #20 !
