### ISSUE TITLE
YouTube videos do not adjust automatically

### ISSUE THREAD

**Issue by Retropex** [wtfhappenedinfeb2023/wtfhappenedinfeb2023.github.io#22]
Probably the same problem as with #19, but `width="100%"` will not be enough because the video is flattened see [here](http://retropex.github.io/wtfhappenedinfeb2023/).

<img width="632" alt="image" src="https://github.com/wtfhappenedinfeb2023/wtfhappenedinfeb2023.github.io/assets/74937347/4f970276-be42-49e2-ae26-f3d9d32d9d7c">

**Comment by piratebiscuit** [comment]
Sorry @Retropex don't know if I'm missing something,but I can't figure out how to solve this one...

**Comment by piratebiscuit** [comment]
@Retropex Even after the next.js update, the height of Youtube videos is still fix.
