### ISSUE TITLE
wtfhappenedinfeb2023.github.io shouldn't redirect to 404 error page

### ISSUE THREAD

**Issue by GregTonoski** [wtfhappenedinfeb2023/wtfhappenedinfeb2023.github.io#42]
There are links to wtfhappenedinfeb2023.github.io in the Internet. If people click it then they see 404 error. Instead they should be redirected to "https://wtfhappenedinfeb2023.com".

Perhaps, index.html with redirection would work, e.g.:
```
<!DOCTYPE html>
<html>
    <head>
     <meta charset="UTF-8" />
     <meta http-equiv="refresh" content="0; URL=https://wtfhappenedinfeb2023.com" />
   </head>
   <body>
   </body>
</html>
```

**Comment by Retropex** [comment]
thanks I forgot to take this link into account during the rework.

**Comment by GregTonoski** [comment]
Tested. Works fine now.
